server:
  port: 8080
  mode: debug # debug or release

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["*"]
  expose_headers: ["Content-Length"]
  allow_credentials: true
  max_age: 12h
